[package]
name = "quilt"
version = "0.1.0"
authors = ["Jack Byrne <jgbyrne9@gmail.com>"]

[dependencies]
walkdir = "2"
pulldown-cmark = {version = "0.0.11", default-features = false }
time = "0.1"
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"
rocket = "0.3.6"
rocket_codegen = "0.3.6"
